table '01_Expressão Única'
	lineageTag: 475e48d0-5309-4b30-b722-770bac403afb

	column 'Cód Funcionário'
		dataType: int64
		formatString: 0
		lineageTag: 0aa1abdf-6bff-4550-aceb-b126b2e9bff0
		summarizeBy: sum
		sourceColumn: Cód Funcionário

		annotation SummarizationSetBy = Automatic

	column Funcionário
		dataType: string
		lineageTag: 3e095d51-c490-421c-a667-98a6eb6c82cf
		summarizeBy: none
		sourceColumn: Funcionário

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: 8850d20c-e268-4cd2-8e42-5b465a52ce13
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column 'Data Admissão'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ead3bbe2-bd76-42e0-8baf-5582c78d572c
		summarizeBy: none
		sourceColumn: Data Admissão

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cód Cargo'
		dataType: int64
		formatString: 0
		lineageTag: 11b20504-4baf-4d99-a8ad-5a7b0aa7732e
		summarizeBy: sum
		sourceColumn: Cód Cargo

		annotation SummarizationSetBy = Automatic

	column Cargo
		dataType: string
		lineageTag: c4aec39c-2c1f-4a02-82c2-3d9ce2fd5538
		summarizeBy: none
		sourceColumn: Cargo

		annotation SummarizationSetBy = Automatic

	column 'Data Cargo'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 459f2779-06a8-4313-9a4a-7e7003b6b883
		summarizeBy: none
		sourceColumn: Data Cargo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cód Escala'
		dataType: int64
		formatString: 0
		lineageTag: 8b1d9f56-bd49-4a85-ad44-5bd113dfe9e8
		summarizeBy: sum
		sourceColumn: Cód Escala

		annotation SummarizationSetBy = Automatic

	column Escala
		dataType: string
		lineageTag: 146f8639-c837-4b79-b34f-31b7f6806a3c
		summarizeBy: none
		sourceColumn: Escala

		annotation SummarizationSetBy = Automatic

	column 'Cód C.Custo'
		dataType: string
		lineageTag: 2524f899-54e8-4937-ab42-5f1f3ec77e39
		summarizeBy: none
		sourceColumn: Cód C.Custo

		annotation SummarizationSetBy = Automatic

	column 'Centro Custo'
		dataType: string
		lineageTag: 1393b6f0-ae5c-4c59-8157-d4f97a4ab80e
		summarizeBy: none
		sourceColumn: Centro Custo

		annotation SummarizationSetBy = Automatic

	column 'Cód T. Contrato'
		dataType: int64
		formatString: 0
		lineageTag: f1d31704-61b9-474f-9f44-a97b93d67ed2
		summarizeBy: sum
		sourceColumn: Cód T. Contrato

		annotation SummarizationSetBy = Automatic

	column 'Tipo Contrato'
		dataType: string
		lineageTag: 3d491d20-9141-4f24-9b12-ca161e5579a3
		summarizeBy: none
		sourceColumn: Tipo Contrato

		annotation SummarizationSetBy = Automatic

	column 'Cód Estado Civil'
		dataType: int64
		formatString: 0
		lineageTag: 2de48844-5c20-45c8-8cb5-a8edc196c732
		summarizeBy: sum
		sourceColumn: Cód Estado Civil

		annotation SummarizationSetBy = Automatic

	column 'Estado Civil'
		dataType: string
		lineageTag: 34d13ccb-b4c3-4c2c-b1d9-4c96835d0fe9
		summarizeBy: none
		sourceColumn: Estado Civil

		annotation SummarizationSetBy = Automatic

	column 'Cód Escolaridade'
		dataType: int64
		formatString: 0
		lineageTag: 0a211523-0b82-4f59-b0d3-108018bc695f
		summarizeBy: sum
		sourceColumn: Cód Escolaridade

		annotation SummarizationSetBy = Automatic

	column Escolaridade
		dataType: string
		lineageTag: d533c048-02f1-4c41-9947-ef25535a1c9e
		summarizeBy: none
		sourceColumn: Escolaridade

		annotation SummarizationSetBy = Automatic

	column 'Data Nascimento'
		dataType: string
		lineageTag: a9674ea3-fdfb-4dcc-a3a7-3f3e201ffb6c
		summarizeBy: none
		sourceColumn: Data Nascimento

		annotation SummarizationSetBy = Automatic

	column 'Cód Nacionalidade'
		dataType: int64
		formatString: 0
		lineageTag: f946d1f5-e37f-4911-8c7a-3e9cf68492da
		summarizeBy: sum
		sourceColumn: Cód Nacionalidade

		annotation SummarizationSetBy = Automatic

	column Nacionalidade
		dataType: string
		lineageTag: 44e98080-791c-429c-ba52-074cf67b63fb
		summarizeBy: none
		sourceColumn: Nacionalidade

		annotation SummarizationSetBy = Automatic

	column 'Cód Raça'
		dataType: int64
		formatString: 0
		lineageTag: b1c721f9-466f-45b3-bd64-428473c9c093
		summarizeBy: sum
		sourceColumn: Cód Raça

		annotation SummarizationSetBy = Automatic

	column Raça
		dataType: string
		lineageTag: ca4d685e-7e5e-4936-87da-6e0604bab809
		summarizeBy: none
		sourceColumn: Raça

		annotation SummarizationSetBy = Automatic

	column 'Valor Salário'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 78e3cbd1-a420-407e-aee2-1b986aee467d
		summarizeBy: sum
		sourceColumn: Valor Salário

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Data Salário'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3d15c640-d1e9-44ba-a08b-3035602238cf
		summarizeBy: none
		sourceColumn: Data Salário

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cód Situação'
		dataType: int64
		formatString: 0
		lineageTag: 02a683db-99b6-4b1f-995b-62f6e0ddf27d
		summarizeBy: sum
		sourceColumn: Cód Situação

		annotation SummarizationSetBy = Automatic

	column Situação
		dataType: string
		lineageTag: f0e4e8d5-aa52-4adb-a00d-b5b0c83e5294
		summarizeBy: none
		sourceColumn: Situação

		annotation SummarizationSetBy = Automatic

	column 'Data Afastamento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: acbfc388-387a-45cf-bf50-9f670ba1e6e5
		summarizeBy: none
		sourceColumn: Data Afastamento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cód Causa Afastamento'
		dataType: int64
		formatString: 0
		lineageTag: 7f30856f-e85d-4055-964f-a57af17ee707
		summarizeBy: sum
		sourceColumn: Cód Causa Afastamento

		annotation SummarizationSetBy = Automatic

	column 'Causa Afastamento'
		dataType: string
		lineageTag: 65a81b77-648d-47e0-a751-a74c7caaa388
		summarizeBy: none
		sourceColumn: Causa Afastamento

		annotation SummarizationSetBy = Automatic

	partition '01_Expressão Única' = m
		mode: import
		queryGroup: 'Tipos de Expressões'
		source =
				Table.RemoveRowsWithErrors(
				    Table.TransformColumnTypes(
				        Table.PromoteHeaders(
				            Excel.Workbook(
				                File.Contents("C:\Users\Smaley\Documents\Smaley\Cursos\Xperiun\APIs e Linguagem M Avançado\data\Funcionarios.xlsx"),null,true
				            ){[Item="Planilha1", Kind="Sheet"]}[Data],
				            [PromoteAllScalars=true]
				        ),
				        {
				            {"Cód Funcionário", Int64.Type},{"Funcionário", type text},{"Sexo", type text},{"Data Admissão", type date},{"Cód Cargo", Int64.Type},{"Cargo", type text},{"Data Cargo", type date},{"Cód Escala", Int64.Type},{"Escala", type text},{"Cód C.Custo", type text},{"Centro Custo", type text},{"Cód T. Contrato", Int64.Type},{"Tipo Contrato", type text},{"Cód Estado Civil", Int64.Type},{"Estado Civil", type text},{"Cód Escolaridade", Int64.Type},{"Escolaridade", type text},{"Data Nascimento", type text},{"Cód Nacionalidade", Int64.Type},{"Nacionalidade", type text},{"Cód Raça", Int64.Type},{"Raça", type text},{"Valor Salário", Currency.Type},{"Data Salário", type date},{"Cód Situação", Int64.Type},{"Situação", type text},{"Data Afastamento", type date},{"Cód Causa Afastamento", Int64.Type},{"Causa Afastamento", type text}
				        }
				    ),
				    {"Data Afastamento"}
				)

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

